trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  rith: 'Secret'

jobs:
- job: Build
  displayName: 'Testing Building'
  steps:
  - script: |
      echo "Hello"
  - powershell: |
      echo "##vso[task.setvariable variable=test]$(rith)"
    displayName: 'Variable setting is being done Rithwik'
  - powershell: |
      echo "Value of var is $(test)"
    displayName: 'Printing Varibale Value Rithwik'
