trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  test: 'Rithwik Bojja'

jobs:
- job: Build
  displayName: 'Test Build'
  steps:
  - script: |
      echo "Hello"
  - script: |
      echo "##vso[task.setvariable variable=rivar;isOutput=true]$(test)"
  - script: |
      echo "Output variable value: $(rivar)"
    displayName: 'Value of Variable set'
