trigger:
  branches:
    include:
      - main

parameters:
  - name: Test
    type: boolean
    default: true

jobs:
  - job: Build
    steps:
      - script: echo "Hello Rithwik Bojjam The value of Test param is ${{ parameters.Foo }}"
        displayName: 'Rithwik is Printing Bollean value'
