trigger:
  branches:
    include:
      - main

parameters:
  - name: Test
    type: boolean
    default: true

jobs:
- job: Test
  steps:
  - script: echo $(Test)
    condition: and(succeeded(), eq('${{ parameters.Foo }}', 'true'))
  - script: echo "Test is false"
    condition: and(succeeded(), eq('${{ parameters.Foo }}', 'false'))
