trigger:
- main

pool:
  vmImage: 'windows-latest'

jobs:
- job: RegisterScheduledRunbook
  displayName: 'Register Scheduled Runbook'
  steps:
  - checkout: self  # Assuming you are checking out the repository

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'rithwiktesy'  
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: |
        Install-Module -Name Az -Force -Scope CurrentUser -AllowClobber
        Import-Module -Name Az -Force
        $automationAccount = "rithwik98"
        $automationRg = "v-rbojja-Mindtree"
        $runBookName = "rithwik"
        $TimeZone = "Australia/Sydney"
        $deleteContainerAppIn = 4
        $brand = "test"
        $startTime = [System.DateTimeOffset]::Now.AddHours($deleteContainerAppIn)
        Write-Host "Calculated Start Time: $startTime"
        $scheduler = New-AzAutomationSchedule -AutomationAccountName $automationAccount -Name "$brand-aa-sch-eau" -OneTime -ResourceGroupName $automationRg -StartTime $startTime -TimeZone $TimeZone
        Write-Host "Schedule created: $($scheduler.Name)"
        Register-AzAutomationScheduledRunbook -AutomationAccountName $automationAccount -ResourceGroupName $automationRg -RunbookName $runBookName -ScheduleName $scheduler.Name -Parameters @{
          'RESOURCEGROUP' = 'v-rbojja-Mindtree'
          'APPNAME' = 'test-app-del'
          'SUBSCRIPTIONID' = 'test-sub'
          'BRAND' = 'MS'
          'ENV' = 'dev'
        } -ErrorAction Stop -Verbose -Debug
        Write-Host "Scheduled runbook registered successfully."
