trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  automationAccount: 'rithwik98'
  automationRg: 'v-rbojja-Mindtree'
  runBookName: 'rithwik'
  TimeZone: 'Australia/Sydney'
  deleteContainerAppIn: 4  
  brand: 'test'

jobs:
- job: RegisterScheduledRunbook
  displayName: 'Register Scheduled Runbook'
  steps:
  - checkout: self  # Assuming you are checking out the repository

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'github.com_Rithwik-Bojja'  # Use the ARM service connection name here
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Define variables
        $automationAccount = "${{ variables.automationAccount }}"
        $automationRg = "${{ variables.automationRg }}"
        $runBookName = "${{ variables.runBookName }}"
        $TimeZone = "${{ variables.TimeZone }}"
        $deleteContainerAppIn = ${{ variables.deleteContainerAppIn }}
        $brand = "${{ variables.brand }}"
        
        # Calculate the start time by adding the specified number of hours to the current time
        $startTime = [System.DateTimeOffset]::Now.AddHours($deleteContainerAppIn)
        
        # Authenticate with Azure
        Connect-AzAccount -Identity

        # Check if the runbook exists
        $runbook = Get-AzAutomationRunbook -AutomationAccountName $automationAccount -Name $runBookName -ResourceGroupName $automationRg
        
        # Create the schedule
        $scheduler = New-AzAutomationSchedule -AutomationAccountName $automationAccount -Name "$brand-aa-sch-eau" -OneTime -ResourceGroupName $automationRg -StartTime $startTime -TimeZone $TimeZone
        
        # Register the scheduled runbook
        Register-AzAutomationScheduledRunbook -AutomationAccountName $automationAccount -ResourceGroupName $automationRg -RunbookName $runBookName -ScheduleName $scheduler.Name -Parameters @{
          'RESOURCEGROUP' = 'v-rbojja-Mindtree'
          'APPNAME' = 'test-app-del'
          'SUBSCRIPTIONID' = 'test-sub'
          'BRAND' = 'MS'
          'ENV' = 'dev'
        } -ErrorAction Stop -Verbose -Debug
