trigger:
  branches:
    include:
      - main

parameters:
  - name: Test
    type: boolean
    default: true

jobs:
  - job: Build
    steps:
       - script: echo $(Test)
    condition: and(succeeded(), eq('${{ parameters.Test }}', 'true'))
  - script: echo "Test is false"
    condition: and(succeeded(), eq('${{ parameters.Test }}', 'false'))
