trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Static hardcoded example
  hardcodedValue: 'myRgName1,myRgName2'

steps:
- task: AzureCLI@2
  displayName: 'Demonstrate Variable vs Hardcoded Value in Azure CLI Command'
  inputs:
    azureSubscription: 'rithres'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Hardcoded value
      hardcodedValue='$(hardcodedValue)'
      echo "Hardcoded Value: $hardcodedValue"

      # Dynamically resolve a value
      echo "Fetching resource group names dynamically..."
      preDeploymentRgList=$(az group list --subscription "ACES CORE-BAMI-MT-V-RBOJJA" --query "[].name" -o tsv)
      echo "Resource Group List from az group list command: $preDeploymentRgList"

      # Convert to a comma-separated string
      dynamicValue=$(echo "$preDeploymentRgList" | tr '\n' ',' | sed 's/,$//')
      echo "Dynamic Value (Comma-Separated): $dynamicValue"

      # Compare the values
      echo "Comparing Values:"
      echo "Hardcoded: $hardcodedValue"
      echo "Dynamic: $dynamicValue"
