trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  rith_hd_vl: 'rithwik,rithpyser'

steps:
- task: AzureCLI@2
  displayName: 'Rithwik Test'
  inputs:
    azureSubscription: 'rithres'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      rith_hd_vl='$(rith_hd_vl)'
      echo "Hello Rithwik, Hardcoded Value is: $rith_hd_vl"

      rith_rg_list=$(az group list --subscription "ACES CORE-BAMI-MT-V-RBOJJA" --query "[].name" -o tsv)
      echo "Hello Rithwik, Output of az group list cmd is : $rith_rg_list"

      ri_dv=$(echo "$rith_rg_list" | tr '\n' ' ' | sed 's/,$//')
      ri_dv=""
      while IFS= read -r line; do
        dynamicValue+="$line"
      done <<< "$preDeploymentRgList"
      echo "Dynamic Value (Comma-Separated): $ri_dv"
