trigger:
  branches:
    include:
      - main

parameters:
  - name: Test
    type: boolean
    default: true

jobs:
  - job: Build
    steps:
      - script: echo "Hello Rithwik Bojja, The value of Test param is ${{ parameters.Test }}"
        displayName: 'Rithwik is Printing Bollean value'
