jobs:
- job: Rithwik_Job1
  displayName: 'Rithwik_Job1'
  steps:
  - pwsh: ./rith.ps1 
    name: rithtask

- job: Rithwik_Job2
  displayName: 'Rithwik_Job2'
  dependsOn: Rithwik_Job1
  condition: eq(dependencies.Job1.outputs['myTaskName.buildScope'], 'public')
  steps:
  - script: echo "Hello Rithwik your testScope is public"
