jobs:
- job: Job1
  displayName: 'Job 1'
  steps:
  - pwsh: ./rith.ps1 
    name: myTaskName
  - powershell: |
      # Check the value of the output variable
      if ("$(myTaskName.buildScope)" -eq "public") {
        echo "Do something based on buildScope"
      } else {
        echo "Skip further actions because buildScope is not public"
        exit 0  # Exit with success code to skip subsequent steps
      }
    displayName: 'Run PowerShell script'

  - script: echo "Continue with additional steps"
    displayName: 'Echo message'
