jobs:
- job: Rithwik_Job
  displayName: 'Rithwik_Job'
  steps:
  - pwsh: ./rith.ps1 
    name: rithtask
  - script: |
           if ("$(rithtask.buildScope)" -eq "public") {
        echo "Hello Rithwik, buildScope is Public"
      } else {
        echo "Hello Rithwik, rithtask is not public"
        exit 0 
      }
  - script: echo "Continue with your others steps and operations RithwiK"

