jobs:
- job: Rithwik_Job
  displayName: 'Rithwik_Job'
  steps:
  - pwsh: ./rith.ps1 
    name: rithtask
  - script: |
      if ("$(rithtask.buildScope)" -eq "public") {
        Write-Host "Hello Rithwik, buildScope is Public"
      } else {
        Write-Host "Hello Rithwik, rithtask is not public"
        exit 0        }
  - script: echo "Continue with your others steps and operations Rithwik"
